service: freelo-skill

frameworkVersion: ">=1.4.0 <2.0.0"

package:
  exclude:
    - node_modules/eslint/**
    - node_modules/chai/**
    - node_modules/mocha/**
    - .git/**
    - src

provider:
  name: aws
  runtime: nodejs6.10

functions:
  skill:
    handler: build/bundle.handler
    events:
      - alexaSkill
